#version 460 core
layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D imgOut;

#define M_PI 3.1415926535897932384626433832795
const float inf = 100000000.f;
const float EQUAL_FLOATS_EPS = 0.1f;

// STRUCTS

struct deviceVertexData{
	vec4 pos;
	vec4 col;
};

// 32 + 8 + 8 = 48
struct deviceBVHNode{
    vec4 aabbMin, aabbMax; // 4 * 8
    int leftChild, itemCount; //2 * 4
    int padding1, padding2; //2 * 4
};

struct MonteCarloParams{
	int vertexN;
	float eps;
	int sampleN;
	int maxWalk;
};

struct indexStruct{
    int pos;
    int _padding1, _padding2, _padding3;
};

struct algorithmOptStruct{
    int pass;
    int isBVH, _padding2, _padding3;   
};

// SSBOs

layout(std430, binding = 0) readonly buffer ssbo0{
	deviceVertexData boundingPoints[];
};

layout(std430, binding = 1) readonly buffer ssbo1{
    MonteCarloParams monteCarloParams;
};

layout(std430, binding = 2) readonly buffer ssbo2{
    deviceBVHNode bvhElems[];
};

layout(std430, binding = 3) readonly buffer BVHIndexingSsbo {
    indexStruct pointIndex[];
};

layout(std430, binding = 4) readonly buffer algorithmSsbo {
    algorithmOptStruct opts;
};

//==============================================================
//Rand function from Visual Studio
//Actual source: https://www.shadertoy.com/view/WdXfzl
int seed = 1;
int rand(void) { seed = seed*0x343fd+0x269ec3; return (seed>>16)&32767; }
float frand(void) { return float(rand())/32767.0; }
void  srand( ivec2 p, int frame ){
    int n = frame;
    n = (n<<13)^n; n=n*(n*n*15731+789221)+1376312589; // by Hugo Elias
    n += p.y;
    n = (n<<13)^n; n=n*(n*n*15731+789221)+1376312589;
    n += p.x;
    n = (n<<13)^n; n=n*(n*n*15731+789221)+1376312589;
    seed = n;
}
//==============================================================

float getMaxDistFromBVH(vec4 x_o, int elemIdx){
    deviceBVHNode elem = bvhElems[elemIdx];
    return max(length(elem.aabbMax - x_o), length(x_o - elem.aabbMin));
}

float distFromBVH(vec4 x_o, deviceBVHNode elem){
    vec4 pb = min(max(x_o, elem.aabbMin), elem.aabbMax);
    return length(x_o - pb);
}

int testBVHDistQuery(vec4 x_o, float maxDist){
    int nodeIdx = 0;
    int stackPtr = 0;
    int nodeStack[32];

    float minDist = inf;
    float dist;
    int closestBoundIdx = -1;

    while(true){
        deviceBVHNode node = bvhElems[nodeIdx];
        if(distFromBVH(x_o, node) <=maxDist){
            if(node.itemCount > 0){
                for(int i = node.leftChild; i < node.leftChild + node.itemCount; ++i){
                    dist = length(x_o - boundingPoints[pointIndex[i].pos].pos);
                    if(dist <= maxDist){
                        maxDist = dist;
                        closestBoundIdx = pointIndex[i].pos;
                    }
                }
            }else{
                int leftChildIdx = node.leftChild;
                int rightChildIdx = node.leftChild + 1;
                float distFromLeft = distFromBVH(x_o, bvhElems[leftChildIdx]);
                float distFromRight = distFromBVH(x_o, bvhElems[rightChildIdx]);

                if(distFromRight < distFromLeft){
                    if(distFromLeft <= maxDist) {
                        nodeStack[stackPtr++] = leftChildIdx;
                        maxDist = max(maxDist, getMaxDistFromBVH(x_o, leftChildIdx));
                    }
                    if(distFromRight <= maxDist) {
                        nodeStack[stackPtr++] = rightChildIdx;
                        maxDist = max(maxDist, getMaxDistFromBVH(x_o, rightChildIdx));
                    }
                }else{
                    if(distFromRight <= maxDist){ 
                        nodeStack[stackPtr++] = rightChildIdx;
                        maxDist = max(maxDist, getMaxDistFromBVH(x_o, rightChildIdx));
                    }
                    if(distFromLeft <= maxDist){
                        nodeStack[stackPtr++] = leftChildIdx;
                        maxDist = max(maxDist, getMaxDistFromBVH(x_o, leftChildIdx));
                    }
                }
            } 
        }
  
        if(stackPtr < 1) return closestBoundIdx;
        nodeIdx = nodeStack[--stackPtr];
    }
}



deviceVertexData closestPointBVH(vec4 x_o, float maxDist){
    if(opts.isBVH == 0){
        float closest = inf;
        deviceVertexData value = boundingPoints[0];
        for(int i = 0; i < monteCarloParams.vertexN; ++i){
            float dist = length(x_o - boundingPoints[i].pos);
            if(dist < closest) {
                closest = dist;
                value = boundingPoints[i];
            }
        }  
        
        return value;
    }

    int nodeStack[32];
    int stackIdx = 0;
    nodeStack[stackIdx++] = 0;
    
    float closest = inf;
    deviceVertexData value = boundingPoints[0];

    while(stackIdx > 0){
        int nodeIdx = nodeStack[--stackIdx];
        deviceBVHNode node = bvhElems[nodeIdx];
        
        if(node.itemCount > 0){ 
            for(int i = node.leftChild; i < node.leftChild + node.itemCount; ++i){
                float dist = length(x_o - boundingPoints[pointIndex[i].pos].pos);
                if(dist < closest) {
                    closest = dist;
                    value = boundingPoints[pointIndex[i].pos];
                }
            }
        }else{
            int leftChildIdx = node.leftChild;
            int rightChildIdx = node.leftChild + 1;
            deviceBVHNode leftChild = bvhElems[leftChildIdx];
            deviceBVHNode rightChild = bvhElems[rightChildIdx];

            float lenLeft = distFromBVH(x_o, leftChild);
            float lenRight = distFromBVH(x_o, rightChild);

            if(lenLeft < lenRight){
                if(lenRight < closest) nodeStack[stackIdx++] = rightChildIdx;
                if(lenLeft < closest) nodeStack[stackIdx++] = leftChildIdx;
            }else{
                if(lenLeft < closest) nodeStack[stackIdx++] = leftChildIdx;
                if(lenRight < closest) nodeStack[stackIdx++] = rightChildIdx;
            }
        }
    }

    return value;
}

vec4 MonteCarloEstim(vec4 x_o){
    int it = 0;
    deviceVertexData closestPoint = closestPointBVH(x_o, inf);
    float radius = length(x_o - closestPoint.pos);
    while(it < monteCarloParams.maxWalk && radius > monteCarloParams.eps) {  
        it++;
        float th = frand() * 2 * M_PI;
        x_o = vec4(x_o.x + radius * cos(th), x_o.y + radius * sin(th), x_o.zw);
        closestPoint = closestPointBVH(x_o, radius);
        radius = length(x_o - closestPoint.pos);
    }

    if(it == monteCarloParams.maxWalk) return vec4(0.,0.,0.,1.);
    return closestPoint.col;   
}

void main(){
    int pass = opts.pass;
	srand(ivec2(gl_GlobalInvocationID.xy), int(pass));

    vec4 sum = vec4(0.0, 0.0, 0.0, 0.0);
    vec4 realCoord;
    for(int i = 0; i < monteCarloParams.sampleN; ++i){
        realCoord = vec4(gl_GlobalInvocationID, 1.0);
        sum += MonteCarloEstim(realCoord);
    }

    sum += imageLoad(imgOut, ivec2(gl_GlobalInvocationID.xy));
    imageStore(imgOut, ivec2(gl_GlobalInvocationID.xy), sum);
}